module Development
  class BootPod
    GS_FILE: String
    GB_FILE: String
    SB_FILE: String

    def boot_data: -> String

    def fetch_data?: -> bool

    def patch_file?: -> bool

    def patch_path?: -> bool

    def provide_options: -> array[hash[String, String]]

    def run_deploy?: -> bool

    def run_update?: -> bool
  end
end
