module Development
  class BootPod
    def fetch_data: -> bool

    def patch_data: -> bool

    def patch_file: -> bool

    def create: -> String

    def deploy: -> String

    def update: -> String
  end
end
