module Development
  class JavaPod
    private

    def fetch_data?: -> bool

    def patch_build?: -> bool

    def patch_file?: -> bool

    def patch_items?: -> bool

    def patch_path?: -> bool

    def provide_options: -> array[hash[String, String]]

    def run_deploy?: -> bool

    def run_update?: -> bool
  end
end
