module Development
  class JavaPod
    private

    def conf_data: -> String

    def libs_data: -> String

    def repo_data: -> String

    def test_data: -> String

    def unit_data: -> String

    def fetch_data?: -> bool

    def patch_build?: -> bool

    def patch_file?: -> bool

    def patch_items?: -> bool

    def patch_path?: -> bool

    def provide_options: -> array[hash[String, String]]

    def run_deploy?: -> bool

    def run_update?: -> bool

    def sub_map: -> hash[String, String]
  end
end
