module Development
  class RubyPod
    def fetch_data?: -> bool

    def patch_data?: -> bool

    def patch_file?: -> bool

    def provide_options: -> array[untyped]

    def setup_core?: -> bool

    def update_options?: -> bool

    def create: -> int
  end
end
