module Development
  class RubyPod
    def fetch_data?: -> bool

    def patch_file?: -> bool

    def patch_gemspec?: -> bool

    def patch_path?: -> bool

    def provide_options: -> array[hash[String, String]]

    def ruby_data: -> String

    def run_deploy?: -> bool

    def run_update?: -> bool

    def spec_file: -> Pathname
  end
end
