module Development
  class VitePod
    def fetch_data: -> bool

    def provide_options: -> array[untyped]

    def setup_core: -> bool

    def update_options: -> untyped

    def create: -> int
  end
end
