module Development
  class VitePod
    def fetch_data?: -> bool

    def patch_file?: -> bool

    def patch_path?: -> bool

    def provide_options: -> array[untyped]

    def run_deploy?: -> bool

    def run_update?: -> bool
  end
end
