module Development
  class CLI

    def create: -> untyped

    def deploy: -> untyped

    def help: -> untyped

    def ping: -> untyped

    def remove: -> untyped

    def tree: -> untyped

    def update: -> untyped

    def version: -> untyped

    def self.exit_on_failure?: -> bool

    def self.start: -> untyped

    private

    def execute_command: (Symbol | nil command) -> untyped
  end
end
