module Development
  class CLI
    def self.exit_on_failure?: -> bool

    def self.start: -> untyped

    def create: -> untyped

    def deploy: -> untyped

    def help: -> untyped

    def ping: -> untyped

    def remove: -> untyped

    def update: -> untyped

    def version: -> untyped
  end
end
