module Development
  DEV_ROOT: String
  CFG_FILE: String
  SRC_FILE: String
  OPT_NAME: String
  RUN_TIME: String
  POD_NAME: String
  TOP_TIME: String
  TOP_USER: String
  GEM_DATA: String
  POD_TYPE: String
  GEM_NAME: String
  CFG_PATH: String
  DEV_PATH: String

  self.@profile: hash[String, String | array[hash[String, String]]]
  self.@runtime: Pod

  def self.runtime_class: -> Class

  def self.secured?: -> bool

  def self.append_timestamp?: -> bool

  def self.data_path: -> String

  def self.entry?: (String entry) -> bool

  def self.operational?: -> bool

  def self.options: -> array[hash[String, String]]

  def self.pod_name: -> String

  def self.remove_timestamp?: -> bool

  def self.runtime: -> Pod

  def self.setup: -> untyped

  def self.update_options?: (array[hash[String, String]] data) -> bool

end
