module Development
  module Hub
    def append_options: (Array[String] tool, ?sep: String) -> untyped

    def copy_item?: (String src_item, String dest_item) -> bool

    def filter_file?: (String file, array[untyped] patterns) -> bool

    def move_item?: (String src_item, String dest_item) -> bool

    def run_pipeline?: (String path, array[untyped] tools) -> bool

    def run_tools?: (String path, array[untyped] tools) -> bool

    def setup_core?: -> bool

    def token_gsub?: (String file, String original, String replacement) -> bool

    def update_file?: (String file, String mode, String data) -> bool

    def update_options?: -> bool
  end
end
