module Development
  class Pod
    ECHO_FILE: String
    VERSION: String

    def safe_remove: -> bool

    def append_options: (Array[String] tool, ?sep: String) -> untyped

    def item_copy: (String src_dir, String dest_dir) -> bool

    def item_move: (String src_dir, String dest_dir) -> bool

    def create: -> String

    def deploy: -> String

    def ping: -> String

    def remove: -> String

    def update: -> String

    def version: -> String
  end
end
