module Development
  class Pod
    ECHO_FILE: String
    BASE_COLOR: String
    FAIL_COLOR: String
    PASS_COLOR: String
    WARN_COLOR: String
    FAIL_LABEL: String
    PASS_LABEL: String
    WARN_LABEL: String
    STOP_LABEL: String
    VERSION: String

    def create: -> int

    def deploy: -> int

    def ping: -> int

    def remove: -> int

    def update: -> int

    def version: -> int

    private

    def execute_task: (Symbol | nil method_name, ?noop: bool) { -> bool } -> int

    def log_failure: (Symbol | nil method_name) -> untyped

    def log_outcome: (Symbol | nil method_name, bool res_ok, ?extra_message: String | nil) -> untyped

    def log_warning: (Symbol | nil method_name) -> untyped

    def read_data: (String file) -> String

    def safe_remove?: -> bool

    def select_color: (bool res_ok) -> String

    def select_label: (bool res_ok) -> String
  end
end
