module Development
  class Pod
    ECHO_FILE: String
    VERSION: String

    def create: -> String

    def deploy: -> String

    def append_options: (*Array[String] tool) -> untyped

    def ping: -> String

    def remove: -> String

    def run_all: (*Array[String] toolset) -> bool

    def safe_remove: -> bool

    def update: -> String

    def version: -> String
  end
end
