module Development
  CFG_NAME: String
  CFG_PATH: String
  GEM_NAME: String

  self.@profile: untyped
  self.@runtime: Pod

  def self.configured?: -> bool

  def self.data_path: -> untyped

  def self.options: -> untyped

  def self.setup: -> untyped

  def self.runtime_class: -> Class

  def self.runtime: -> Pod
end
